'use client';

import { useEffect, useRef, useState } from 'react';
import JSZip from 'jszip';
import { toast } from 'sonner';
import { AppShell } from '@/components/layout/app-shell';
import { ChatPanel, fixPreviewWithAi } from '@/components/builder/chat-panel';
import { TopBar } from '@/components/builder/top-bar';
import { PreviewPanel } from '@/components/builder/preview-panel';
import { useAuth } from '@/components/providers/auth-provider';
import { saveProjectBundle } from '@/lib/project-service';
import { useBuilderStore } from '@/lib/store/builder-store';
import { IS_STATIC_EXPORT } from '@/lib/runtime';

export default function BuilderPage() {
  const splitHandleRef = useRef<HTMLDivElement | null>(null);
  const { user } = useAuth();
  const { projectId, projectName, files, versions, messages, loadProject, setSaving, markSaved } =
    useBuilderStore();
  const [mounted, setMounted] = useState(false);
  const [chatWidth, setChatWidth] = useState(540);
  const [resizing, setResizing] = useState(false);

  const exportProject = async () => {
    const currentFiles = useBuilderStore.getState().files;
    const currentProjectName = useBuilderStore.getState().projectName || 'codedai-project';

    if (IS_STATIC_EXPORT) {
      const zip = new JSZip();

      Object.entries(currentFiles).forEach(([path, content]) => {
        zip.file(path, content);
      });

      if (!currentFiles['README.md']) {
        zip.file(
          'README.md',
          `# ${currentProjectName}\n\nGenerated by CodedAI.\n\n## Run locally\n\n1. npm install\n2. npm run dev\n\n## Deploy\n\nUse Vercel and add your env vars.`
        );
      }

      if (!currentFiles['vercel.json']) {
        zip.file('vercel.json', JSON.stringify({ framework: 'nextjs' }, null, 2));
      }

      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${currentProjectName}.zip`;
      link.click();
      URL.revokeObjectURL(url);
      toast.success('Project exported');
      return;
    }

    const response = await fetch('/api/export', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ projectName: currentProjectName, files: currentFiles })
    });

    if (!response.ok) {
      toast.error('Export failed');
      return;
    }

    const blob = await response.blob();
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${currentProjectName}.zip`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success('Project exported');
  };

  const deployProject = async () => {
    const repositoryUrl = window.prompt('Paste your GitHub/GitLab/Bitbucket repo URL to deploy on Vercel:');
    if (!repositoryUrl) return;

    const requiredEnvKeys = [
      'OPENAI_API_KEY',
      'NEXT_PUBLIC_FIREBASE_API_KEY',
      'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
      'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
      'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
      'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
      'NEXT_PUBLIC_FIREBASE_APP_ID'
    ];

    try {
      const host = new URL(repositoryUrl).hostname.toLowerCase();
      if (!['github.com', 'gitlab.com', 'bitbucket.org'].includes(host)) {
        toast.error('Repository URL must be from GitHub, GitLab, or Bitbucket');
        return;
      }

      const params = new URLSearchParams();
      params.set('repository-url', repositoryUrl);
      params.set('env', requiredEnvKeys.join(','));
      params.set('project-name', useBuilderStore.getState().projectName);
      window.open(`https://vercel.com/new/clone?${params.toString()}`, '_blank', 'noopener,noreferrer');
      toast.success('Opened one-click Vercel deploy');
    } catch {
      toast.error('Invalid repository URL');
    }
  };

  useEffect(() => {
    setMounted(true);
    try {
      const savedWidth = window.localStorage.getItem('codedai-chat-width');
      if (savedWidth) {
        const parsed = Number(savedWidth);
        if (!Number.isNaN(parsed)) {
          setChatWidth(parsed);
        }
      }
    } catch {
      // Ignore localStorage read issues.
    }
  }, []);

  useEffect(() => {
    try {
      window.localStorage.setItem('codedai-chat-width', String(chatWidth));
    } catch {
      // Ignore localStorage write issues.
    }
  }, [chatWidth]);

  useEffect(() => {
    if (!resizing) {
      return;
    }

    const onPointerMove = (event: PointerEvent) => {
      const shell = splitHandleRef.current?.parentElement;
      if (!shell) {
        return;
      }

      const bounds = shell.getBoundingClientRect();
      const nextWidth = event.clientX - bounds.left;
      const minWidth = 420;
      const maxWidth = Math.min(760, bounds.width - 420);
      setChatWidth(Math.max(minWidth, Math.min(maxWidth, nextWidth)));
    };

    const onPointerUp = () => setResizing(false);

    window.addEventListener('pointermove', onPointerMove);
    window.addEventListener('pointerup', onPointerUp);

    return () => {
      window.removeEventListener('pointermove', onPointerMove);
      window.removeEventListener('pointerup', onPointerUp);
    };
  }, [resizing]);

  if (!mounted) return null;

  return (
    <AppShell contentClassName="grid min-h-0 grid-rows-[auto_1fr] gap-4">
      <>
        <TopBar
          onExport={exportProject}
          onDeploy={deployProject}
          onSave={async () => {
            try {
              setSaving(true);
              const bundle = await saveProjectBundle({
                ownerId: user?.uid ?? 'guest',
                projectId,
                name: projectName,
                files,
                versions,
                messages
              });

              loadProject({
                projectId: bundle.project.id,
                projectName: bundle.project.name,
                files: bundle.files,
                versions: bundle.versions,
                messages: bundle.messages
              });
              markSaved();
              toast.success(user ? 'Project saved' : 'Project saved locally');
            } catch (error) {
              toast.error(error instanceof Error ? error.message : 'Project save failed');
            } finally {
              setSaving(false);
            }
          }}
        />

        <section
          className="grid min-h-0 grid-cols-1 gap-5 xl:gap-0"
          style={{
            gridTemplateColumns:
              typeof window !== 'undefined' && window.innerWidth >= 1280
                ? `${chatWidth}px 18px minmax(0, 1fr)`
                : 'minmax(0, 1fr)'
          }}
        >
          <ChatPanel projectId={projectId} />
          <div
            ref={splitHandleRef}
            className={`relative hidden xl:flex xl:items-center xl:justify-center ${resizing ? 'bg-cyan-400/10' : ''}`}
            onPointerDown={() => setResizing(true)}
            role="separator"
            aria-orientation="vertical"
            aria-label="Resize chat and preview panels"
          >
            <div className="h-full w-px bg-white/10" />
            <div className="absolute h-24 w-2 cursor-col-resize rounded-full bg-white/20 transition hover:bg-cyan-400/60" />
          </div>
          <PreviewPanel
            files={files}
            onFixWithAi={async (errorText) => {
              try {
                const payload = await fixPreviewWithAi(projectId, files, errorText);
                useBuilderStore.getState().applyAiResponse(payload);
                toast.success('Applied AI fix from preview error');
              } catch (error) {
                toast.error(error instanceof Error ? error.message : 'Fix with AI failed');
              }
            }}
          />
        </section>
      </>
    </AppShell>
  );
}
