"use strict";(()=>{var e={};e.id=252,e.ids=[252],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},92048:e=>{e.exports=require("fs")},32615:e=>{e.exports=require("http")},35240:e=>{e.exports=require("https")},55315:e=>{e.exports=require("path")},68621:e=>{e.exports=require("punycode")},76162:e=>{e.exports=require("stream")},17360:e=>{e.exports=require("url")},21764:e=>{e.exports=require("util")},6162:e=>{e.exports=require("worker_threads")},71568:e=>{e.exports=require("zlib")},87561:e=>{e.exports=require("node:fs")},84492:e=>{e.exports=require("node:stream")},72477:e=>{e.exports=require("node:stream/web")},23197:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>R,patchFetch:()=>j,requestAsyncStorage:()=>A,routeModule:()=>b,serverHooks:()=>P,staticGenerationAsyncStorage:()=>I});var s={};r.r(s),r.d(s,{POST:()=>O,maxDuration:()=>v});var n=r(49303),o=r(88716),a=r(60670),i=r(87070),u=r(54214),p=r(21067);let l=p.Ry({path:p.Z_().min(1),type:p.Km(["upsert","delete"]),content:p.Z_().optional()}),c=p.Ry({assistant_message:p.Z_().min(1),commit_message:p.Z_().min(1),file_ops:p.IX(l).min(1)}),d=p.Ry({instruction:p.Z_().min(1),files:p.IM(p.Z_()),projectMeta:p.Ry({name:p.Z_().optional(),id:p.Z_().optional()}).optional(),errorContext:p.Z_().optional()});function f(e,t,r=Number.POSITIVE_INFINITY){let s=Number(e);return Math.min(Number.isFinite(s)&&s>0?s:t,r)}let m=f(process.env.OPENAI_TIMEOUT_MS,15e4,18e4),h=process.env.OPENAI_MODEL?.trim()||"gpt-5",g=process.env.OPENAI_FALLBACK_MODEL?.trim()||"gpt-4.1",y=process.env.OPENAI_TIMEOUT_FALLBACK_MODEL?.trim()||"gpt-4.1-mini",x=f(process.env.OPENAI_TIMEOUT_FALLBACK_MS,9e4,12e4),v=300,w=`You are CodedAI, a production web app code generator.
Return ONLY JSON and no extra text.
Schema:
{
  "assistant_message": "string",
  "commit_message": "string",
  "file_ops": [
    {"path": "string", "type": "upsert|delete", "content": "string optional for upsert"}
  ]
}
Rules:
- Produce concise but complete changes.
- Default to polished, production-quality results even when the user gives a short prompt.
- Infer tasteful design choices when details are missing and aim for a finished-looking UI, not a bare scaffold.
- Prefer modifying existing files when that keeps the project cleaner, but create new files freely when it improves structure.
- Support creating, editing, and deleting files across app, components, styles, scripts, assets, and config.
- You may add JavaScript, TypeScript, JSX, TSX, CSS, JSON, Markdown, and public asset files.
- Do not wait for the user to ask for extra files, CSS, or JavaScript. Add them automatically whenever they improve quality, maintainability, or visual polish.
- For non-trivial pages, proactively split large code into reusable components and supporting style files instead of one oversized page file.
- Make layouts responsive by default and include thoughtful spacing, typography, hierarchy, and hover/focus states when relevant.
- Avoid bland default output. Choose a clear visual direction with strong styling and sensible motion when appropriate.
- The live builder preview does not compile Tailwind utilities or Next.js-only features reliably.
- Prefer standard CSS in app/globals.css or imported CSS files, relative imports, and client-renderable React components.
- Do not rely on @apply, Tailwind class names, next/font, server-only code, or @/ path aliases unless the user explicitly asks for that tradeoff.
- If you create a new file, wire it into the existing entry points when needed so the feature is actually used.
- Keep the project runnable with the current dependency set and favor browser-safe React code.
- You may output CSS, TSX, JSON, Markdown, and other project files as needed.
- Never include markdown fences.
- Refuse disallowed harmful requests and return safe minimal changes.
`;function _(e){if(!(e instanceof Error))return!1;let t=e.message.toLowerCase(),r=e.name.toLowerCase();return r.includes("abort")||r.includes("timeout")||t.includes("timed out")||t.includes("abort")}async function N(e,t,r,s=m){let n=new AbortController,o=!1,a=setTimeout(()=>{o=!0,n.abort()},s);try{let o=await e.responses.create({model:r,input:[{role:"system",content:[{type:"input_text",text:w}]},{role:"user",content:[{type:"input_text",text:t}]}],text:{format:{type:"json_object"}},temperature:.3},{signal:n.signal,timeout:s});return o.output_text?.trim()??""}catch(e){if(o)throw Error(`OpenAI request timed out after ${Math.round(s/1e3)}s`);throw e}finally{clearTimeout(a)}}async function S(e,t){try{return await N(e,t,h)}catch(r){if(function(e){if("object"!=typeof e||null===e)return!1;let t="status"in e?e.status:void 0,r="message"in e?String(e.message??""):"";return(400===t||404===t)&&r.toLowerCase().includes("model")}(r))return N(e,t,g);if(_(r)&&y!==h)return N(e,t,y,x);throw r}}async function O(e){let t=process.env.OPENAI_API_KEY?.trim();if(!t)return i.NextResponse.json({error:"Missing OPENAI_API_KEY. Add it to .env.local and restart dev server. Use /app/settings for setup instructions."},{status:400});try{var r;let s;let n=await e.json(),o=d.safeParse(n);if(!o.success)return i.NextResponse.json({error:"Invalid input payload"},{status:400});let a=new u.ZP({apiKey:t,maxRetries:0}),p=(r=o.data,JSON.stringify({instruction:r.instruction,projectMeta:r.projectMeta??null,errorContext:r.errorContext??null,previewCapabilities:{renderer:"sandpack-react",supportsNextRuntime:!1,supportsTailwindProcessing:!1,supportsPathAliases:!1,stylingPreference:"plain-css-or-css-modules"},files:r.files},null,2)),l=await S(a,p);try{s=JSON.parse(l)}catch{l=await S(a,`${p}

Return ONLY valid JSON. No commentary.`),s=JSON.parse(l)}let f=c.safeParse(s);if(!f.success){l=await S(a,`${p}

The previous answer was invalid. Return ONLY valid JSON matching schema.`),s=JSON.parse(l);let e=c.safeParse(s);if(!e.success)return i.NextResponse.json({error:"AI returned invalid JSON structure"},{status:502});return i.NextResponse.json(e.data)}return i.NextResponse.json(f.data)}catch(e){if("object"==typeof e&&null!==e&&"status"in e&&401===e.status)return i.NextResponse.json({error:"OpenAI auth failed (401). Check OPENAI_API_KEY and restart the server."},{status:401});if(_(e))return i.NextResponse.json({error:"OpenAI took too long to respond. Please try again."},{status:504});return i.NextResponse.json({error:e instanceof Error?e.message:"Unexpected AI route error"},{status:500})}}let b=new n.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/ai/route",pathname:"/api/ai",filename:"route",bundlePath:"app/api/ai/route"},resolvedPagePath:"/workspaces/codefreed.github.io/app/api/ai/route.ts",nextConfigOutput:"",userland:s}),{requestAsyncStorage:A,staticGenerationAsyncStorage:I,serverHooks:P}=b,R="/api/ai/route";function j(){return(0,a.patchFetch)({serverHooks:P,staticGenerationAsyncStorage:I})}}};var t=require("../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),s=t.X(0,[948,972,67,214],()=>r(23197));module.exports=s})();