import { NextResponse } from 'next/server';
import JSZip from 'jszip';
import { z } from 'zod';

const schema = z.object({
  projectName: z.string().default('codedai-project'),
  files: z.record(z.string())
});

export async function POST(req: Request) {
  try {
    const parsed = schema.safeParse(await req.json());
    if (!parsed.success) {
      return NextResponse.json({ error: 'Invalid export payload' }, { status: 400 });
    }

    const zip = new JSZip();

    Object.entries(parsed.data.files).forEach(([path, content]) => {
      zip.file(path, content);
    });

    if (!parsed.data.files['README.md']) {
      zip.file(
        'README.md',
        `# ${parsed.data.projectName}\n\nGenerated by CodedAI.\n\n## Run locally\n\n1. npm install\n2. npm run dev\n\n## Deploy\n\nUse Vercel and add your env vars.`
      );
    }

    if (!parsed.data.files['vercel.json']) {
      zip.file('vercel.json', JSON.stringify({ framework: 'nextjs' }, null, 2));
    }

    const blob = await zip.generateAsync({ type: 'nodebuffer' });

    return new NextResponse(blob as unknown as BodyInit, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${parsed.data.projectName}.zip"`
      }
    });
  } catch {
    return NextResponse.json({ error: 'Export failed' }, { status: 500 });
  }
}
